"""empty message

Revision ID: 707d8bae8fde
Revises: cef2985b5fab
Create Date: 2017-02-06 02:44:47.679290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707d8bae8fde'
down_revision = 'cef2985b5fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('proposal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dates_proposal_id'), 'dates', ['proposal_id'], unique=False)
    op.drop_index('ix_dates_meal_time', table_name='dates')
    op.drop_index('ix_dates_proposal_user_id', table_name='dates')
    op.drop_index('ix_dates_request_id', table_name='dates')
    op.drop_index('ix_dates_request_user_id', table_name='dates')
    op.drop_constraint(None, 'dates', type_='foreignkey')
    op.drop_constraint(None, 'dates', type_='foreignkey')
    op.drop_constraint(None, 'dates', type_='foreignkey')
    op.create_foreign_key(None, 'dates', 'proposals', ['proposal_id'], ['id'])
    op.drop_column('dates', 'proposal_user_id')
    op.drop_column('dates', 'meal_date')
    op.drop_column('dates', 'request_user_id')
    op.drop_column('dates', 'meal_time')
    op.drop_column('dates', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('request_id', sa.INTEGER(), nullable=True))
    op.add_column('dates', sa.Column('meal_time', sa.VARCHAR(length=32), nullable=True))
    op.add_column('dates', sa.Column('request_user_id', sa.INTEGER(), nullable=True))
    op.add_column('dates', sa.Column('meal_date', sa.DATETIME(), nullable=True))
    op.add_column('dates', sa.Column('proposal_user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'dates', type_='foreignkey')
    op.create_foreign_key(None, 'dates', 'users', ['proposal_user_id'], ['id'])
    op.create_foreign_key(None, 'dates', 'users', ['request_user_id'], ['id'])
    op.create_foreign_key(None, 'dates', 'requests', ['request_id'], ['id'])
    op.create_index('ix_dates_request_user_id', 'dates', ['request_user_id'], unique=False)
    op.create_index('ix_dates_request_id', 'dates', ['request_id'], unique=False)
    op.create_index('ix_dates_proposal_user_id', 'dates', ['proposal_user_id'], unique=False)
    op.create_index('ix_dates_meal_time', 'dates', ['meal_time'], unique=False)
    op.drop_index(op.f('ix_dates_proposal_id'), table_name='dates')
    op.drop_column('dates', 'proposal_id')
    # ### end Alembic commands ###
