"""empty message

Revision ID: cef2985b5fab
Revises: 59765cc966ea
Create Date: 2017-02-04 04:12:46.294245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef2985b5fab'
down_revision = '59765cc966ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('request_user_id', sa.Integer(), nullable=True),
    sa.Column('proposal_user_id', sa.Integer(), nullable=True),
    sa.Column('meal_date', sa.DateTime(), nullable=True),
    sa.Column('meal_time', sa.String(length=32), nullable=True),
    sa.Column('restaurant_name', sa.String(length=256), nullable=True),
    sa.Column('restaurant_address', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['proposal_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['request_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dates_meal_time'), 'dates', ['meal_time'], unique=False)
    op.create_index(op.f('ix_dates_proposal_user_id'), 'dates', ['proposal_user_id'], unique=False)
    op.create_index(op.f('ix_dates_request_id'), 'dates', ['request_id'], unique=False)
    op.create_index(op.f('ix_dates_request_user_id'), 'dates', ['request_user_id'], unique=False)
    op.create_index(op.f('ix_dates_restaurant_address'), 'dates', ['restaurant_address'], unique=False)
    op.create_index(op.f('ix_dates_restaurant_name'), 'dates', ['restaurant_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dates_restaurant_name'), table_name='dates')
    op.drop_index(op.f('ix_dates_restaurant_address'), table_name='dates')
    op.drop_index(op.f('ix_dates_request_user_id'), table_name='dates')
    op.drop_index(op.f('ix_dates_request_id'), table_name='dates')
    op.drop_index(op.f('ix_dates_proposal_user_id'), table_name='dates')
    op.drop_index(op.f('ix_dates_meal_time'), table_name='dates')
    op.drop_table('dates')
    # ### end Alembic commands ###
